name: Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Build
        env:
          GITHUB_TOKEN_RO: ${{ secrets.GH_TOKEN_RO }}
        run: |
          npm install
          npm run build

      - name: Copy Docs
        run: cp -R ./docs ./build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: build

